### ISSUE TITLE
Icon links to file:///

### ISSUE THREAD

**Issue by RhodesPeter** [The-Authenticators/sohapp#49]
When I click on your icon at the top left of your screen I get directed here: <br>
![screen shot 2016-12-21 at 10 54 19](https://cloud.githubusercontent.com/assets/18164707/21386679/dcba4008-c76b-11e6-82f1-2fb5ee48f553.png)
🙀

**Comment by emilyb7** [comment]
This is exactly what I wanted to happen, what's the problem?! 😆
