### ISSUE TITLE
Defining functions inside listeners

### ISSUE THREAD

**Issue by eliasmalik** [The-Authenticators/sohapp#63]
Minor point, and only significant at larger scales, but putting your function definition inside your listener [here](https://github.com/The-Authenticators/sohapp/blob/master/js/app.js) means it will be defined and then destroyed each time the listener is called. It's more efficient if you define it in another scope (for example in a module) and then just reference it.

**Comment by marisid** [comment]
Point taken - I've moved the function declaration outside the event listener. Cheers! PR awaiting merging.
