### ISSUE TITLE
Confusing conditional

### ISSUE THREAD

**Issue by eliasmalik** [The-Authenticators/sohapp#64]
Having two embedded if statements that have the same condition [here](https://github.com/The-Authenticators/sohapp/blob/master/js/app.js#L14-L18) is on the face of it a bit confusing to a reader. I had to spend a little while working out why it might be necessary. Would be nice to help a reader with a comment on potentially unclear bits of code like this.

**Comment by marisid** [comment]
I've added a comment (maybe not so explicit). Good shout!
